
description_text1 = 'We print high quality reproductions of historical maps, photographs, prints, etc. Because of their historical nature, some of these images may show signs of wear and tear - small rips, stains, creases, etc. We believe that in many cases this contributes to the historical character of the item.'
'\nHowever, we also do some retouching work to every image that we print, adjusting for color correctness, contrast, sharpness, as well as fixing small blemishes. We use our experience and judgment when deciding how much to edit each image. We will usually remove distracting elements like library stamps, or a single tear or fold. However, we also don\'t want to go overboard and make a map from 1718 look like it was released in 2018.'
'\nSo, take a close look at the preview image. What you see is, by and large, what you will get, with some enhancements. If you have any questions about how much your image might be edited, just contact us and we will let you know.'

description_text2 = 'We print high quality reproductions of historical maps, photographs and prints. Some of these images may show signs of wear and tear - we believe that in many cases this contributes to the aesthetics of the item.'
'\nWe also do some retouching work to our products, adjusting for color correctness, contrast, sharpness, as well as fixing small blemishes. If you have any questions about how much your image might be edited, just contact us and we will let you know.'

description_text3 = 'Some of these images may show signs of wear and tear - we believe that in many cases this contributes to the aesthetics of the item.'
'\nWe adjust for color correctness, contrast, sharpness, and fix small blemishes. If you have any questions about how much your image might be edited, just contact us and we will let you know.'